[package]
name = "yagl"
version = "0.1.0"
authors = ["Kyumin Kim <math4tots@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
a2d = "0.1.4"
anyhow = "1.0"
futures = "0.3.4"
