use crate::winit::event::VirtualKeyCode;

/// A key on the keyboard
///
/// Currently just mirrors the keys recognized by winit
///
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum Key {
    /// The '1' key over the letters.
    Key1,
    /// The '2' key over the letters.
    Key2,
    /// The '3' key over the letters.
    Key3,
    /// The '4' key over the letters.
    Key4,
    /// The '5' key over the letters.
    Key5,
    /// The '6' key over the letters.
    Key6,
    /// The '7' key over the letters.
    Key7,
    /// The '8' key over the letters.
    Key8,
    /// The '9' key over the letters.
    Key9,
    /// The '0' key over the 'O' and 'P' keys.
    Key0,

    A,
    B,
    C,
    D,
    E,
    F,
    G,
    H,
    I,
    J,
    K,
    L,
    M,
    N,
    O,
    P,
    Q,
    R,
    S,
    T,
    U,
    V,
    W,
    X,
    Y,
    Z,

    /// The Escape key, next to F1.
    Escape,

    F1,
    F2,
    F3,
    F4,
    F5,
    F6,
    F7,
    F8,
    F9,
    F10,
    F11,
    F12,
    F13,
    F14,
    F15,
    F16,
    F17,
    F18,
    F19,
    F20,
    F21,
    F22,
    F23,
    F24,

    /// Print Screen/SysRq.
    Snapshot,
    /// Scroll Lock.
    Scroll,
    /// Pause/Break key, next to Scroll lock.
    Pause,

    /// `Insert`, next to Backspace.
    Insert,
    Home,
    Delete,
    End,
    PageDown,
    PageUp,

    Left,
    Up,
    Right,
    Down,

    /// The Backspace key, right over Enter.
    // TODO: rename
    Backspace,
    /// The Enter key.
    Return,
    /// The space bar.
    Space,

    /// The "Compose" key on Linux.
    Compose,

    Caret,

    Numlock,
    Numpad0,
    Numpad1,
    Numpad2,
    Numpad3,
    Numpad4,
    Numpad5,
    Numpad6,
    Numpad7,
    Numpad8,
    Numpad9,

    AbntC1,
    AbntC2,
    Add,
    Apostrophe,
    Apps,
    At,
    Ax,
    Backslash,
    Calculator,
    Capital,
    Colon,
    Comma,
    Convert,
    Decimal,
    Divide,
    Equals,
    Grave,
    Kana,
    Kanji,
    LAlt,
    LBracket,
    LControl,
    LShift,
    LWin,
    Mail,
    MediaSelect,
    MediaStop,
    Minus,
    Multiply,
    Mute,
    MyComputer,
    NavigateForward,  // also called "Prior"
    NavigateBackward, // also called "Next"
    NextTrack,
    NoConvert,
    NumpadComma,
    NumpadEnter,
    NumpadEquals,
    OEM102,
    Period,
    PlayPause,
    Power,
    PrevTrack,
    RAlt,
    RBracket,
    RControl,
    RShift,
    RWin,
    Semicolon,
    Slash,
    Sleep,
    Stop,
    Subtract,
    Sysrq,
    Tab,
    Underline,
    Unlabeled,
    VolumeDown,
    VolumeUp,
    Wake,
    WebBack,
    WebFavorites,
    WebForward,
    WebHome,
    WebRefresh,
    WebSearch,
    WebStop,
    Yen,
    Copy,
    Paste,
    Cut,
}

impl Key {
    pub(crate) fn from_winit(code: VirtualKeyCode) -> Option<Key> {
        match code {
            VirtualKeyCode::Key1 => Some(Key::Key1),
            VirtualKeyCode::Key2 => Some(Key::Key2),
            VirtualKeyCode::Key3 => Some(Key::Key3),
            VirtualKeyCode::Key4 => Some(Key::Key4),
            VirtualKeyCode::Key5 => Some(Key::Key5),
            VirtualKeyCode::Key6 => Some(Key::Key6),
            VirtualKeyCode::Key7 => Some(Key::Key7),
            VirtualKeyCode::Key8 => Some(Key::Key8),
            VirtualKeyCode::Key9 => Some(Key::Key9),
            VirtualKeyCode::Key0 => Some(Key::Key0),
            VirtualKeyCode::A => Some(Key::A),
            VirtualKeyCode::B => Some(Key::B),
            VirtualKeyCode::C => Some(Key::C),
            VirtualKeyCode::D => Some(Key::D),
            VirtualKeyCode::E => Some(Key::E),
            VirtualKeyCode::F => Some(Key::F),
            VirtualKeyCode::G => Some(Key::G),
            VirtualKeyCode::H => Some(Key::H),
            VirtualKeyCode::I => Some(Key::I),
            VirtualKeyCode::J => Some(Key::J),
            VirtualKeyCode::K => Some(Key::K),
            VirtualKeyCode::L => Some(Key::L),
            VirtualKeyCode::M => Some(Key::M),
            VirtualKeyCode::N => Some(Key::N),
            VirtualKeyCode::O => Some(Key::O),
            VirtualKeyCode::P => Some(Key::P),
            VirtualKeyCode::Q => Some(Key::Q),
            VirtualKeyCode::R => Some(Key::R),
            VirtualKeyCode::S => Some(Key::S),
            VirtualKeyCode::T => Some(Key::T),
            VirtualKeyCode::U => Some(Key::U),
            VirtualKeyCode::V => Some(Key::V),
            VirtualKeyCode::W => Some(Key::W),
            VirtualKeyCode::X => Some(Key::X),
            VirtualKeyCode::Y => Some(Key::Y),
            VirtualKeyCode::Z => Some(Key::Z),
            VirtualKeyCode::Escape => Some(Key::Escape),
            VirtualKeyCode::F1 => Some(Key::F1),
            VirtualKeyCode::F2 => Some(Key::F2),
            VirtualKeyCode::F3 => Some(Key::F3),
            VirtualKeyCode::F4 => Some(Key::F4),
            VirtualKeyCode::F5 => Some(Key::F5),
            VirtualKeyCode::F6 => Some(Key::F6),
            VirtualKeyCode::F7 => Some(Key::F7),
            VirtualKeyCode::F8 => Some(Key::F8),
            VirtualKeyCode::F9 => Some(Key::F9),
            VirtualKeyCode::F10 => Some(Key::F10),
            VirtualKeyCode::F11 => Some(Key::F11),
            VirtualKeyCode::F12 => Some(Key::F12),
            VirtualKeyCode::F13 => Some(Key::F13),
            VirtualKeyCode::F14 => Some(Key::F14),
            VirtualKeyCode::F15 => Some(Key::F15),
            VirtualKeyCode::F16 => Some(Key::F16),
            VirtualKeyCode::F17 => Some(Key::F17),
            VirtualKeyCode::F18 => Some(Key::F18),
            VirtualKeyCode::F19 => Some(Key::F19),
            VirtualKeyCode::F20 => Some(Key::F20),
            VirtualKeyCode::F21 => Some(Key::F21),
            VirtualKeyCode::F22 => Some(Key::F22),
            VirtualKeyCode::F23 => Some(Key::F23),
            VirtualKeyCode::F24 => Some(Key::F24),
            VirtualKeyCode::Snapshot => Some(Key::Snapshot),
            VirtualKeyCode::Scroll => Some(Key::Scroll),
            VirtualKeyCode::Pause => Some(Key::Pause),
            VirtualKeyCode::Insert => Some(Key::Insert),
            VirtualKeyCode::Home => Some(Key::Home),
            VirtualKeyCode::Delete => Some(Key::Delete),
            VirtualKeyCode::End => Some(Key::End),
            VirtualKeyCode::PageDown => Some(Key::PageDown),
            VirtualKeyCode::PageUp => Some(Key::PageUp),
            VirtualKeyCode::Left => Some(Key::Left),
            VirtualKeyCode::Up => Some(Key::Up),
            VirtualKeyCode::Right => Some(Key::Right),
            VirtualKeyCode::Down => Some(Key::Down),
            VirtualKeyCode::Back => Some(Key::Backspace),
            VirtualKeyCode::Return => Some(Key::Return),
            VirtualKeyCode::Space => Some(Key::Space),
            VirtualKeyCode::Compose => Some(Key::Compose),
            VirtualKeyCode::Caret => Some(Key::Caret),
            VirtualKeyCode::Numlock => Some(Key::Numlock),
            VirtualKeyCode::Numpad0 => Some(Key::Numpad0),
            VirtualKeyCode::Numpad1 => Some(Key::Numpad1),
            VirtualKeyCode::Numpad2 => Some(Key::Numpad2),
            VirtualKeyCode::Numpad3 => Some(Key::Numpad3),
            VirtualKeyCode::Numpad4 => Some(Key::Numpad4),
            VirtualKeyCode::Numpad5 => Some(Key::Numpad5),
            VirtualKeyCode::Numpad6 => Some(Key::Numpad6),
            VirtualKeyCode::Numpad7 => Some(Key::Numpad7),
            VirtualKeyCode::Numpad8 => Some(Key::Numpad8),
            VirtualKeyCode::Numpad9 => Some(Key::Numpad9),
            VirtualKeyCode::AbntC1 => Some(Key::AbntC1),
            VirtualKeyCode::AbntC2 => Some(Key::AbntC2),
            VirtualKeyCode::Add => Some(Key::Add),
            VirtualKeyCode::Apostrophe => Some(Key::Apostrophe),
            VirtualKeyCode::Apps => Some(Key::Apps),
            VirtualKeyCode::At => Some(Key::At),
            VirtualKeyCode::Ax => Some(Key::Ax),
            VirtualKeyCode::Backslash => Some(Key::Backslash),
            VirtualKeyCode::Calculator => Some(Key::Calculator),
            VirtualKeyCode::Capital => Some(Key::Capital),
            VirtualKeyCode::Colon => Some(Key::Colon),
            VirtualKeyCode::Comma => Some(Key::Comma),
            VirtualKeyCode::Convert => Some(Key::Convert),
            VirtualKeyCode::Decimal => Some(Key::Decimal),
            VirtualKeyCode::Divide => Some(Key::Divide),
            VirtualKeyCode::Equals => Some(Key::Equals),
            VirtualKeyCode::Grave => Some(Key::Grave),
            VirtualKeyCode::Kana => Some(Key::Kana),
            VirtualKeyCode::Kanji => Some(Key::Kanji),
            VirtualKeyCode::LAlt => Some(Key::LAlt),
            VirtualKeyCode::LBracket => Some(Key::LBracket),
            VirtualKeyCode::LControl => Some(Key::LControl),
            VirtualKeyCode::LShift => Some(Key::LShift),
            VirtualKeyCode::LWin => Some(Key::LWin),
            VirtualKeyCode::Mail => Some(Key::Mail),
            VirtualKeyCode::MediaSelect => Some(Key::MediaSelect),
            VirtualKeyCode::MediaStop => Some(Key::MediaStop),
            VirtualKeyCode::Minus => Some(Key::Minus),
            VirtualKeyCode::Multiply => Some(Key::Multiply),
            VirtualKeyCode::Mute => Some(Key::Mute),
            VirtualKeyCode::NextTrack => Some(Key::NextTrack),
            VirtualKeyCode::NoConvert => Some(Key::NoConvert),
            VirtualKeyCode::NumpadComma => Some(Key::NumpadComma),
            VirtualKeyCode::NumpadEnter => Some(Key::NumpadEnter),
            VirtualKeyCode::NumpadEquals => Some(Key::NumpadEquals),
            VirtualKeyCode::OEM102 => Some(Key::OEM102),
            VirtualKeyCode::Period => Some(Key::Period),
            VirtualKeyCode::PlayPause => Some(Key::PlayPause),
            VirtualKeyCode::Power => Some(Key::Power),
            VirtualKeyCode::PrevTrack => Some(Key::PrevTrack),
            VirtualKeyCode::RAlt => Some(Key::RAlt),
            VirtualKeyCode::RBracket => Some(Key::RBracket),
            VirtualKeyCode::RControl => Some(Key::RControl),
            VirtualKeyCode::RShift => Some(Key::RShift),
            VirtualKeyCode::RWin => Some(Key::RWin),
            VirtualKeyCode::Semicolon => Some(Key::Semicolon),
            VirtualKeyCode::Slash => Some(Key::Slash),
            VirtualKeyCode::Sleep => Some(Key::Sleep),
            VirtualKeyCode::Stop => Some(Key::Stop),
            VirtualKeyCode::Subtract => Some(Key::Subtract),
            VirtualKeyCode::Sysrq => Some(Key::Sysrq),
            VirtualKeyCode::Tab => Some(Key::Tab),
            VirtualKeyCode::Underline => Some(Key::Underline),
            VirtualKeyCode::Unlabeled => Some(Key::Unlabeled),
            VirtualKeyCode::VolumeDown => Some(Key::VolumeDown),
            VirtualKeyCode::VolumeUp => Some(Key::VolumeUp),
            VirtualKeyCode::Wake => Some(Key::Wake),
            VirtualKeyCode::WebBack => Some(Key::WebBack),
            VirtualKeyCode::WebFavorites => Some(Key::WebFavorites),
            VirtualKeyCode::WebForward => Some(Key::WebForward),
            VirtualKeyCode::WebHome => Some(Key::WebHome),
            VirtualKeyCode::WebRefresh => Some(Key::WebRefresh),
            VirtualKeyCode::WebSearch => Some(Key::WebSearch),
            VirtualKeyCode::WebStop => Some(Key::WebStop),
            VirtualKeyCode::Yen => Some(Key::Yen),
            VirtualKeyCode::Copy => Some(Key::Copy),
            VirtualKeyCode::Paste => Some(Key::Paste),
            VirtualKeyCode::Cut => Some(Key::Cut),
            _ => None,
        }
    }

    pub const LIST: &'static [Key] = &[
        Key::Key1,
        Key::Key2,
        Key::Key3,
        Key::Key4,
        Key::Key5,
        Key::Key6,
        Key::Key7,
        Key::Key8,
        Key::Key9,
        Key::Key0,
        Key::A,
        Key::B,
        Key::C,
        Key::D,
        Key::E,
        Key::F,
        Key::G,
        Key::H,
        Key::I,
        Key::J,
        Key::K,
        Key::L,
        Key::M,
        Key::N,
        Key::O,
        Key::P,
        Key::Q,
        Key::R,
        Key::S,
        Key::T,
        Key::U,
        Key::V,
        Key::W,
        Key::X,
        Key::Y,
        Key::Z,
        Key::Escape,
        Key::F1,
        Key::F2,
        Key::F3,
        Key::F4,
        Key::F5,
        Key::F6,
        Key::F7,
        Key::F8,
        Key::F9,
        Key::F10,
        Key::F11,
        Key::F12,
        Key::F13,
        Key::F14,
        Key::F15,
        Key::F16,
        Key::F17,
        Key::F18,
        Key::F19,
        Key::F20,
        Key::F21,
        Key::F22,
        Key::F23,
        Key::F24,
        Key::Snapshot,
        Key::Scroll,
        Key::Pause,
        Key::Insert,
        Key::Home,
        Key::Delete,
        Key::End,
        Key::PageDown,
        Key::PageUp,
        Key::Left,
        Key::Up,
        Key::Right,
        Key::Down,
        Key::Backspace,
        Key::Return,
        Key::Space,
        Key::Compose,
        Key::Caret,
        Key::Numlock,
        Key::Numpad0,
        Key::Numpad1,
        Key::Numpad2,
        Key::Numpad3,
        Key::Numpad4,
        Key::Numpad5,
        Key::Numpad6,
        Key::Numpad7,
        Key::Numpad8,
        Key::Numpad9,
        Key::AbntC1,
        Key::AbntC2,
        Key::Add,
        Key::Apostrophe,
        Key::Apps,
        Key::At,
        Key::Ax,
        Key::Backslash,
        Key::Calculator,
        Key::Capital,
        Key::Colon,
        Key::Comma,
        Key::Convert,
        Key::Decimal,
        Key::Divide,
        Key::Equals,
        Key::Grave,
        Key::Kana,
        Key::Kanji,
        Key::LAlt,
        Key::LBracket,
        Key::LControl,
        Key::LShift,
        Key::LWin,
        Key::Mail,
        Key::MediaSelect,
        Key::MediaStop,
        Key::Minus,
        Key::Multiply,
        Key::Mute,
        Key::MyComputer,
        Key::NavigateForward,
        Key::NavigateBackward,
        Key::NextTrack,
        Key::NoConvert,
        Key::NumpadComma,
        Key::NumpadEnter,
        Key::NumpadEquals,
        Key::OEM102,
        Key::Period,
        Key::PlayPause,
        Key::Power,
        Key::PrevTrack,
        Key::RAlt,
        Key::RBracket,
        Key::RControl,
        Key::RShift,
        Key::RWin,
        Key::Semicolon,
        Key::Slash,
        Key::Sleep,
        Key::Stop,
        Key::Subtract,
        Key::Sysrq,
        Key::Tab,
        Key::Underline,
        Key::Unlabeled,
        Key::VolumeDown,
        Key::VolumeUp,
        Key::Wake,
        Key::WebBack,
        Key::WebFavorites,
        Key::WebForward,
        Key::WebHome,
        Key::WebRefresh,
        Key::WebSearch,
        Key::WebStop,
        Key::Yen,
        Key::Copy,
        Key::Paste,
        Key::Cut,
    ];
}
